### ISSUE TITLE
Something may need fix

### ISSUE THREAD

**Issue by wolfoops** [togfoxy/KNN-machine-learning#1]
1. The round function is slow because using string as a conversion medium  of digits.
The same calculation may make with floor (ceil for -ve) like this floor(num * idps [idp] + 0.5) / idps [idp], with idps a preset table of 1.0,10, 100... ie. {[0]=1.0, 10,100, ...} 
2. Likely Typo in getDistanceV  'axis[i] = (inputset[1] - datapoint[1])^2' should the index [1] be [i] ?
3. The axis above is a temporary, it seems the total can be directly calculated without it, ie. 'total = total + (inputset[i] - datapoint[i])^2'

That's it~

**Comment by togfoxy** [comment]
Thanks for those comments. I'll take a look at them soon.  :)

**Comment by togfoxy** [comment]
Thank you for your comments @wolfoops . I have made all the changes you suggested.  :)
